version: '3.8'

services:
  # API NestJS en modo desarrollo
  api-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: baq-api-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    restart: unless-stopped
    networks:
      - baq-dev-network

networks:
  baq-dev-network:
    driver: bridge
